include:
  - '/templates/.defaults.yml'
dply_vm_apply:
  stage: dply_vm_apply
  extends: 
    - .defaults
  script:
    - apk add terraform
    - echo "$SSH_pub_key" | tr -d '\r' > /root/.ssh/cicd.pub
    - cd $CI_PROJECT_DIR/terraform/terraform-proxmox 
    - >
      terraform init 
      -backend-config=address=${GL_TFSTATE_ADDR} 
      -backend-config=lock_address=${GL_TFSTATE_ADDR}/lock 
      -backend-config=unlock_address=${GL_TFSTATE_ADDR}/lock 
      -backend-config=username=${GL_USERNAME} 
      -backend-config=password=${GL_TFSTATE_TOKEN} 
      -backend-config=lock_method=POST 
      -backend-config=unlock_method=DELETE 
      -backend-config=retry_wait_min=5
    - > 
      terraform apply 
      -input=false dply_vm.plan
  rules:
    - if: $TMPLT == null && $VM == null && $K3S == null && $INFRA == "1"
      when: on_success
    - if: $TMPLT == null && $VM == "1" && $K3S == null && $INFRA == null
      when: on_success
    - if: $TMPLT == "1" && $VM == "1" && $K3S == null && $INFRA == null
      when: on_success
    - if: $TMPLT == null && $VM == "1" && $K3S == "1" && $INFRA == null  
      when: on_success
    - when: never
